CBP-27027: Extend s3-upload-object to use register-build-artifact action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2,23 +2,23 @@ apiVersion: automation.cloudbees.io/v1alpha1
 kind: action
 name: upload-s3-object
 inputs:
-  file-path:  # id of input
+  file-path: # id of input
     description: 'Local File Path'
     required: true
-  bucket-name:  # id of input
+  bucket-name: # id of input
     description: 'bucket name'
     required: true
-  s3-path:  # id of input
+  s3-path: # id of input
     description: 's3 path containing object'
     required: true
   send-artifact-info: # id of input
     default: 'false'
     description: 'Send artifact information flag'
     required: true
-  artifact-name:  # Optional input for artifact name
+  artifact-name: # Optional input for artifact name
     description: 'Name of the artifact'
     required: false
-  artifact-version:  # Optional input for artifact version
+  artifact-version: # Optional input for artifact version
     description: 'Version of the artifact'
     required: false
   commit:
@@ -28,12 +28,12 @@ inputs:
     required: false
   repository-url:
     description: >
-        The clone URL of the source repository, used when registering the build artifact in CloudBees platform.
+      The clone URL of the source repository, used when registering the build artifact in CloudBees platform.
     default: ${{ cloudbees.scm.repositoryUrl }}
     required: false
   ref:
     description: >
-        The ref or branch of the source repository, used when registering the build artifact in CloudBees platform.
+      The ref or branch of the source repository, used when registering the build artifact in CloudBees platform.
     default: ${{ cloudbees.scm.ref }}
     required: false
   component-id:
@@ -58,121 +58,145 @@ runs:
         RUN_ID: ${{ cloudbees.run_id }}
         RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
       run: |
-        set -x
-
-        bucketname="${{ inputs.bucket-name }}"
-        s3path="${{ inputs.s3-path }}"
-
-        s3uri="$bucketname"
-
-        # if bucketname does not have s3:// prefix 
-        if [[ $bucketname != s3://* ]]; then
-           bucketname="s3://$bucketname"
-        fi 
-
-        #if s3path does not start with /
-        if [[ $s3path != /* ]]; then
-           s3path="/$s3path"
-        fi 
-        
-        # final s3url
-        s3uri="$bucketname$s3path"
-
-        echo $s3uri
-
-        # Determine if the input is a file or directory
-        if [ ! -f "${{ inputs.file-path }}" ] && [ ! -d "${{ inputs.file-path }}" ]; then
-          echo "Invalid path: ${{ inputs.file-path }} does not exist."
-          exit 1
-        fi
-
-        # File or directory upload logic
-        if [ -f "${{ inputs.file-path }}" ]; then
-          file_name=$(basename "${{ inputs.file-path }}")
-          file_type="file"
-          aws s3 cp ${{ inputs.file-path }} $s3uri | tee "${{cloudbees.workspace}}/aws_response.txt"
-          etag=$(aws s3api head-object --bucket ${{ inputs.bucket-name }} --key ${{ inputs.s3-path }} --query 'ETag' --output text)
-        elif [ -d "${{ inputs.file-path }}" ]; then
-          file_name=$(basename "${{ inputs.file-path }}")
-          file_type="folder"
-          aws s3 cp ${{ inputs.file-path }} $s3uri --recursive | tee "${{cloudbees.workspace}}/aws_response.txt"
-        fi 
-        grep upload: "${{cloudbees.workspace}}/aws_response.txt" | sed 's/.*upload: //' | awk '{print "| " $1 " | " $3 " |"}' | tee "$CLOUDBEES_OUTPUTS/s3_upload_evidence"
-
-        # Determine the artifact name: use provided artifact name or fallback to file name
-        artifact_name="${{ inputs.artifact-name }}"
-        if [ -z "$artifact_name" ]; then
-          artifact_name="$file_name"
-        fi
-
-        # Handle Artifact API call only if `send-artifact-info` is true
-        if [[ "${{ inputs.send-artifact-info }}" == "true" ]]; then
-          # Prepare API payload
-          imgName="$artifact_name"
-          imgVer="${{ inputs.artifact-version }}"
-          if [ -z "$imgVer" ]; then
-            imgVer="-"
-          fi
-
-          artifact_type="file"
-          if [ "$file_type" == "folder" ]; then
-            artifact_type="folder"
-          fi
-
-          destination="$s3uri"
-        
-          commit="${{ inputs.commit }}"
-          repository_url="${{ inputs.repository-url }}"
-          ref="${{ inputs.ref }}"
-          component_id="${{ inputs.component-id }}"
-        
-          echo "Publishing build artifact information"
-
-          # Construct the basic JSON payload
-          json_payload='{
-            "runId": "'"$RUN_ID"'",
-            "runAttempt": '"$RUN_ATTEMPT"',
-            "name": "'"$imgName"'",
-            "version": "'"$imgVer"'",
-            "url": "'"$destination"'",
-            "type": "'"$artifact_type"'",
-            "componentId": "'"$component_id"'",
-            "commit": {
-              "repositoryUrl": "'"$repository_url"'",
-              "commitId": "'"$commit"'",
-              "ref": "'"$ref"'"
-            }}'
-
-          # If $etag is not empty, add the "digest" field directly to the JSON
-         if [[ -n "$etag" ]]; then
-           json_payload=$(echo "$json_payload" | sed "s/}}$/},\n  \"digest\": \"${etag//\"/}\" \n}/")
-         fi
-
-          # API call to publish artifact info
-          response=$(curl --retry-delay 5 --retry 3 --retry-connrefused --fail-with-body -X 'POST' "$CLOUDBEES_API_URL/v3/artifactinfos" \
-            -H "Authorization: Bearer $CLOUDBEES_API_TOKEN" \
-            -H 'Content-Type: application/json' \
-            --data-binary "$json_payload") || command_failed=1
-
-          # Check curl exit code
-          if [ ${command_failed:-0} -eq 1 ]; then
-            echo "ERROR: failed to save artifact information: '$response'"
-            exit 1
-          else
-            echo "Artifact details pushed to CloudBees platform successfully"
-            
-            # Extract the artifactId
-            id=$(echo "$response" | grep -o '"id": *"[^"]*"' | sed 's/.*"id": *"\([^"]*\)".*/\1/')
+             set -x
+             
+             bucketname="${{ inputs.bucket-name }}"
+             s3path="${{ inputs.s3-path }}"
+             
+             s3uri="$bucketname"
+             
+             # if bucketname does not have s3:// prefix 
+             if [[ $bucketname != s3://* ]]; then
+             bucketname="s3://$bucketname"
+             fi 
+             
+             #if s3path does not start with /
+             if [[ $s3path != /* ]]; then
+             s3path="/$s3path"
+             fi 
+             
+             # final s3url
+             s3uri="$bucketname$s3path"
+             
+             echo $s3uri
+             
+             # Determine if the input is a file or directory
+             if [ ! -f "${{ inputs.file-path }}" ] && [ ! -d "${{ inputs.file-path }}" ]; then
+             echo "Invalid path: ${{ inputs.file-path }} does not exist."
+             exit 1
+             fi
+             
+             # File or directory upload logic
+             if [ -f "${{ inputs.file-path }}" ]; then
+             file_name=$(basename "${{ inputs.file-path }}")
+             file_type="file"
+             aws s3 cp ${{ inputs.file-path }} $s3uri | tee "${{cloudbees.workspace}}/aws_response.txt"
+             etag=$(aws s3api head-object --bucket ${{ inputs.bucket-name }} --key ${{ inputs.s3-path }} --query 'ETag' --output text)
+             elif [ -d "${{ inputs.file-path }}" ]; then
+             file_name=$(basename "${{ inputs.file-path }}")
+             file_type="folder"
+             aws s3 cp ${{ inputs.file-path }} $s3uri --recursive | tee "${{cloudbees.workspace}}/aws_response.txt"
+             fi 
+             grep upload: "${{cloudbees.workspace}}/aws_response.txt" | sed 's/.*upload: //' | awk '{print "| " $1 " | " $3 " |"}' | tee "$CLOUDBEES_OUTPUTS/s3_upload_evidence"
+             
+             # Determine the artifact name: use provided artifact name or fallback to file name
+             artifact_name="${{ inputs.artifact-name }}"
+             if [ -z "$artifact_name" ]; then
+             artifact_name="$file_name"
+             fi
+             
+             # Handle Artifact API call only if `send-artifact-info` is true
+             if [[ "${{ inputs.send-artifact-info }}" == "true" ]]; then
+               # Prepare API payload
+               imgName="$artifact_name"
+               imgVer="${{ inputs.artifact-version }}"
+               if [ -z "$imgVer" ]; then
+                imgVer="-"
+               fi
           
-            # Set it as an output
-            printf %s "$id" > $CLOUDBEES_OUTPUTS/artifact-id
-          fi
-        else
-          echo "Artifact information not sent to CloudBees platform"
-          # Output an empty artifact-id output parameter when 
-          # no artifact version info is registered with CloudBees platform
-          echo "" > $CLOUDBEES_OUTPUTS/artifact-id
-        fi
+          #          artifact_type="file"
+          #          if [ "$file_type" == "folder" ]; then
+          #            artifact_type="folder"
+          #          fi
+          
+          #destination="$s3uri"
+          
+          # Set variables to prepare for Artifact API call
+               printf %s "$artifact_name" > $CLOUDBEES_OUTPUTS/image-name
+               printf %s "$imgVer" > $CLOUDBEES_OUTPUTS/image-version
+          #          printf %s "$artifact_type" > $CLOUDBEES_OUTPUTS/artifact-type
+               printf %s "$s3uri" > $CLOUDBEES_OUTPUTS/destination
+          
+          # If $etag is not empty
+               if [[ -n "$etag" ]]; then
+               printf %s "$etag" > $CLOUDBEES_OUTPUTS/digest
+               fi
+          
+          #          commit="${{ inputs.commit }}"
+          #          repository_url="${{ inputs.repository-url }}"
+          #          ref="${{ inputs.ref }}"
+          #          component_id="${{ inputs.component-id }}"
+          #
+          #          echo "Publishing build artifact information"
+          #
+          #          # Construct the basic JSON payload
+          #          json_payload='{
+          #            "runId": "'"$RUN_ID"'",
+          #            "runAttempt": '"$RUN_ATTEMPT"',
+          #            "name": "'"$imgName"'",
+          #            "version": "'"$imgVer"'",
+          #            "url": "'"$destination"'",
+          #            "type": "'"$artifact_type"'",
+          #            "componentId": "'"$component_id"'",
+          #            "commit": {
+          #              "repositoryUrl": "'"$repository_url"'",
+          #              "commitId": "'"$commit"'",
+          #              "ref": "'"$ref"'"
+          #            }}'
+          #
+          #          # If $etag is not empty, add the "digest" field directly to the JSON
+          #         if [[ -n "$etag" ]]; then
+          #           json_payload=$(echo "$json_payload" | sed "s/}}$/},\n  \"digest\": \"${etag//\"/}\" \n}/")
+          #         fi
+          #
+          #          # API call to publish artifact info
+          #          response=$(curl --retry-delay 5 --retry 3 --retry-connrefused --fail-with-body -X 'POST' "$CLOUDBEES_API_URL/v3/artifactinfos" \
+          #            -H "Authorization: Bearer $CLOUDBEES_API_TOKEN" \
+          #            -H 'Content-Type: application/json' \
+          #            --data-binary "$json_payload") || command_failed=1
+          #
+          #          # Check curl exit code
+          #          if [ ${command_failed:-0} -eq 1 ]; then
+          #            echo "ERROR: failed to save artifact information: '$response'"
+          #            exit 1
+          #          else
+          #            echo "Artifact details pushed to CloudBees platform successfully"
+          #
+          #            # Extract the artifactId
+          #            id=$(echo "$response" | grep -o '"id": *"[^"]*"' | sed 's/.*"id": *"\([^"]*\)".*/\1/')
+          #
+          #            # Set it as an output
+          #            printf %s "$id" > $CLOUDBEES_OUTPUTS/artifact-id
+          #          fi
+          #        else
+          #          echo "Artifact information not sent to CloudBees platform"
+          #          # Output an empty artifact-id output parameter when
+          #          # no artifact version info is registered with CloudBees platform
+          #          echo "" > $CLOUDBEES_OUTPUTS/artifact-id
+             fi
+    - id: registerArtifact
+      name: Register Build Artifact
+      if: ${{ inputs.send-artifact-info == 'true' }}
+      uses: cloudbees-io/register-build-artifact@v2
+      with:
+        name: ${{ steps.s3-action-upload.outputs.image-name }}
+        url: ${{ steps.s3-action-upload.outputs.destination }}
+        version: ${{ steps.s3-action-upload.outputs.image-version }}
+        commit: ${{ inputs.commit }}
+        ref: ${{ inputs.ref }}
+        repository-url: ${{ inputs.repository-url }}
+        digest: ${{ steps.s3-action-upload.outputs.digest }}
+        component-id: ${{ inputs.component-id }}
     - name: publish-evidence
       uses: cloudbees-io/publish-evidence-item@v1
       with:
