CBP-27027: outputs value and step name updated

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -43,7 +43,7 @@ inputs:
 
 outputs:
   artifact-id:
-    value: ${{ steps.registerArtifact.outputs.artifact-id }}
+    value: ${{ steps.register-artifact.outputs.artifact-id }}
     description: "The unique identifier of the artifact."
 runs:
   using: composite
@@ -58,77 +58,76 @@ runs:
         RUN_ID: ${{ cloudbees.run_id }}
         RUN_ATTEMPT: ${{ cloudbees.run_attempt }}
       run: |
-             set -x
-             
-             bucketname="${{ inputs.bucket-name }}"
-             s3path="${{ inputs.s3-path }}"
-             
-             s3uri="$bucketname"
-             
-             # if bucketname does not have s3:// prefix 
-             if [[ $bucketname != s3://* ]]; then
-             bucketname="s3://$bucketname"
-             fi 
-             
-             #if s3path does not start with /
-             if [[ $s3path != /* ]]; then
-             s3path="/$s3path"
-             fi 
-             
-             # final s3url
-             s3uri="$bucketname$s3path"
-             
-             echo $s3uri
-             
-             # Determine if the input is a file or directory
-             if [ ! -f "${{ inputs.file-path }}" ] && [ ! -d "${{ inputs.file-path }}" ]; then
-             echo "Invalid path: ${{ inputs.file-path }} does not exist."
-             exit 1
-             fi
-             
-             # File or directory upload logic
-             if [ -f "${{ inputs.file-path }}" ]; then
-              file_name=$(basename "${{ inputs.file-path }}")
-              file_type="file"
-              aws s3 cp ${{ inputs.file-path }} $s3uri | tee "${{cloudbees.workspace}}/aws_response.txt"
-              etag=$(aws s3api head-object --bucket ${{ inputs.bucket-name }} --key ${{ inputs.s3-path }} --query 'ETag' --output text)
-             elif [ -d "${{ inputs.file-path }}" ]; then
-              file_name=$(basename "${{ inputs.file-path }}")
-              file_type="folder"
-              aws s3 cp ${{ inputs.file-path }} $s3uri --recursive | tee "${{cloudbees.workspace}}/aws_response.txt"
-             fi 
-             
-             grep upload: "${{cloudbees.workspace}}/aws_response.txt" | sed 's/.*upload: //' | awk '{print "| " $1 " | " $3 " |"}' | tee "$CLOUDBEES_OUTPUTS/s3_upload_evidence"
-             
-             # Determine the artifact name: use provided artifact name or fallback to file name
-             artifact_name="${{ inputs.artifact-name }}"
-             if [ -z "$artifact_name" ]; then
-              artifact_name="$file_name"
-             fi
-             
-             # Handle Artifact API call only if `send-artifact-info` is true
-             if [[ "${{ inputs.send-artifact-info }}" == "true" ]]; then
-               # Prepare API payload
-               imgName="$artifact_name"
-               imgVer="${{ inputs.artifact-version }}"
-               if [ -z "$imgVer" ]; then
-                imgVer="-"
-               fi
-          
-               # Set variables to prepare for Artifact API call
-               printf %s "$artifact_name" > $CLOUDBEES_OUTPUTS/image-name
-               printf %s "$imgVer" > $CLOUDBEES_OUTPUTS/image-version
-               printf %s "$s3uri" > $CLOUDBEES_OUTPUTS/destination
-          
-               # If $etag is not empty
-               if [[ -n "$etag" ]]; then
-                etag=${etag//\"/}
-                printf %s "$etag" > $CLOUDBEES_OUTPUTS/digest
-               fi
-             fi
-    - id: registerArtifact
+        set -x
+
+        bucketname="${{ inputs.bucket-name }}"
+        s3path="${{ inputs.s3-path }}"
+
+        s3uri="$bucketname"
+
+        # if bucketname does not have s3:// prefix 
+        if [[ $bucketname != s3://* ]]; then
+           bucketname="s3://$bucketname"
+        fi 
+
+        #if s3path does not start with /
+        if [[ $s3path != /* ]]; then
+           s3path="/$s3path"
+        fi 
+        
+        # final s3url
+        s3uri="$bucketname$s3path"
+
+        echo $s3uri
+
+        # Determine if the input is a file or directory
+        if [ ! -f "${{ inputs.file-path }}" ] && [ ! -d "${{ inputs.file-path }}" ]; then
+          echo "Invalid path: ${{ inputs.file-path }} does not exist."
+          exit 1
+        fi
+
+        # File or directory upload logic
+        if [ -f "${{ inputs.file-path }}" ]; then
+          file_name=$(basename "${{ inputs.file-path }}")
+          file_type="file"
+          aws s3 cp ${{ inputs.file-path }} $s3uri | tee "${{cloudbees.workspace}}/aws_response.txt"
+          etag=$(aws s3api head-object --bucket ${{ inputs.bucket-name }} --key ${{ inputs.s3-path }} --query 'ETag' --output text)
+        elif [ -d "${{ inputs.file-path }}" ]; then
+          file_name=$(basename "${{ inputs.file-path }}")
+          file_type="folder"
+          aws s3 cp ${{ inputs.file-path }} $s3uri --recursive | tee "${{cloudbees.workspace}}/aws_response.txt"
+        fi 
+        grep upload: "${{cloudbees.workspace}}/aws_response.txt" | sed 's/.*upload: //' | awk '{print "| " $1 " | " $3 " |"}' | tee "$CLOUDBEES_OUTPUTS/s3_upload_evidence"
+
+        # Determine the artifact name: use provided artifact name or fallback to file name
+        artifact_name="${{ inputs.artifact-name }}"
+        if [ -z "$artifact_name" ]; then
+          artifact_name="$file_name"
+        fi
+
+        # Handle Artifact API call only if `send-artifact-info` is true
+        if [[ "${{ inputs.send-artifact-info }}" == "true" ]]; then
+          # Prepare API payload
+          imgName="$artifact_name"
+          imgVer="${{ inputs.artifact-version }}"
+          if [ -z "$imgVer" ]; then
+            imgVer="-"
+          fi
+
+         # Set variables to prepare for Artifact API call
+         printf %s "$artifact_name" > $CLOUDBEES_OUTPUTS/image-name
+         printf %s "$imgVer" > $CLOUDBEES_OUTPUTS/image-version
+         printf %s "$s3uri" > $CLOUDBEES_OUTPUTS/destination
+
+         # If $etag is not empty
+         if [[ -n "$etag" ]]; then
+          etag=${etag//\"/}
+          printf %s "$etag" > $CLOUDBEES_OUTPUTS/digest
+         fi
+       fi
+    - id: register-artifact
       name: Register Build Artifact
-      if: ${{ inputs.send-artifact-info == true }}
+      if: ${{ inputs.send-artifact-info == 'true' }}
       uses: cloudbees-io/register-build-artifact@v2
       with:
         name: ${{ steps.s3-action-upload.outputs.image-name }}
